### ISSUE TITLE
Failed opening 'TheBuild/IncludeResourceTask.php' for inclusion 

### ISSUE THREAD

**Issue by adityajoshi94** [palantirnet/federated-search-demo#23]
After installation on mac, when i execute vagrant ssh and type phing nothing happens. i installed phing manually i get following error
Failed opening 'TheBuild/IncludeResourceTask.php' for inclusion ((include_path='phar:///usr/bin/phing-latest.phar/bin/.. )

How can i resolved it.

**Comment by jesconstantine** [comment]
Hi @adityajoshi94 - 

Could you provide the output from the following commands: 
- `vagrant up`
- `vagrant ssh` (a [screenshot](https://support.apple.com/en-us/HT201361) would be helpful here)
- `phing build install-all`

That will give us a little more insight into what is happening.

Thanks!

**Comment by adityajoshi94** [comment]
Screenshot for  for vagrant up
<img width="769" alt="Screen Shot 2019-04-03 at 10 09 19 AM" src="https://user-images.githubusercontent.com/5883402/55490195-fc05ce00-55f8-11e9-9f21-a7c941bc88e4.png">
Screenshot for vagrant ssh
<img width="652" alt="Screen Shot 2019-04-03 at 10 03 31 AM" src="https://user-images.githubusercontent.com/5883402/55490261-1a6bc980-55f9-11e9-85a2-23324f2e5ebd.png">
Output of phing build install-all
The program 'phing' is currently not installed. You can install it by typing:
sudo apt install phing

I executed vagrant up using sudo , if it makes any difference
